# -*- coding: utf-8 -*-
"""Program2_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y1FXbXXpP1RUPZ4KayHKZlNIalPqK8wr
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
pd.set_option('display.max_colwidth', -1)
import numpy as np
pd.options.display.max_columns = 100
from sklearn.preprocessing import StandardScaler
import time
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/gdrive/My Drive/Program2/train.dat',header=None,sep=' ')
df1 = pd.read_csv('/content/gdrive/My Drive/Program2/train.labels',header=None)
df2=  pd.read_csv('/content/gdrive/My Drive/Program2/test.dat',header=None,sep=' ')

X = df.iloc[:,:].values
y = df1.iloc[:,:].values
test=df2.iloc[:,:].values

from sklearn.ensemble import RandomForestClassifier

from sklearn.preprocessing import StandardScaler
# standardise the data
X_std = StandardScaler().fit_transform(X)
test_std=StandardScaler().fit_transform(test)

from sklearn.decomposition import PCA

pca = PCA(0.95)

principalComponents = pca.fit_transform(X_std)

principalDf = pd.DataFrame(data = principalComponents)

pca.explained_variance_ratio_

y=y.ravel()

clf = RandomForestClassifier(n_estimators=100,class_weight="balanced")

clf = clf.fit(principalDf,y)

test__pca=pca.transform(test_std)

y_pred = clf.predict(test__pca)

with open('format10.dat','w') as filehandle:
    for listitem in y_pred:
        filehandle.write('%d\n' % listitem)

